[package]
name = "rboy"
version = "0.1.0"
authors = [ "mvdnes <git@mathijs.vd-nes.nl>" ]
edition = "2018"

[dependencies]
blip_buf = { version = ">=0.1.3", optional = true }

[features]
sound = [ "dep:blip_buf" ]
embedded = []

[lib]
name = "rboy"
